Repository JuliaGPU/AMDGPUnative.jl, pull requests merged in 2020-05, with the labels that each got.

#53 Fix kernel indexing
  src/device/gcn/indexing.jl
  test/device/indexing.jl
  test/device/vadd.jl
Labels: bug, enhancement

#57 Properly test error is logged
  test/device/hostcall.jl
Labels: ci

#60 Overhaul README, add Codecov, fix HostKernel in docs
  .gitlab-ci.yml
  README.md
  codecov.yml
  docs/src/api.md
Labels: ci, docs

#63 Support emitting user-specified globals
  Manifest.toml
  Project.toml
  docs/make.jl
  docs/src/api.md
  docs/src/globals.md
  src/AMDGPUnative.jl
  src/device/globals.jl
  src/device/tools.jl
  src/execution.jl
  src/execution_utils.jl
  src/runtime.jl
  test/device/globals.jl
  test/runtests.jl
Labels: enhancement
